<?php

/* Linfo
 *
 * Copyright (c) 2018 Joe Gillotti
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

namespace Linfo\Lang;

/*
 * English translation
 */

return array(
    'header' => 'System Health and Information',
    'core' => 'Core',
    'os' => 'OS',
    'kernel' => 'Kernel',
    'accessed_ip' => 'Accessed IP',
    'uptime' => 'Uptime',
    'hostname' => 'Hostname',
    'cpus' => 'CPUs',
    'phpversion' => 'PHP version',
    'webservice' => 'HTTP server',
    'load' => 'Load',
    'processes' => 'Processes',
    'threads' => 'Threads',
    'total' => 'Total',
    'memory' => 'Memory',
    'type' => 'Type',
    'free' => 'Free',
    'used' => 'Used',
    'size' => 'Size',
    'physical' => 'Physical',
    'swap' => 'Swap',
    'network_devices' => 'Network Devices',
    'device_name' => 'Device Name',
    'amount_sent' => 'Amount Sent',
    'amount_received' => 'Amount Received',
    'state' => 'State',
    'temps_voltages' => 'Temperatures / Voltages',
    'path' => 'Path',
    'device' => 'Device',
    'value' => 'Value',
    'hardware' => 'Hardware',
    'vendor' => 'Vendor',
    'drives' => 'Drives',
    'name' => 'Name',
    'reads' => 'Reads',
    'writes' => 'Writes',
    'filesystem_mounts' => 'Filesystem Mounts',
    'mount_point' => 'Mount Point',
    'filesystem' => 'Filesystem',
    'percent_used' => 'Percent Used',
    'raid_arrays' => 'RAID Arrays',
    'level' => 'Level',
    'status' => 'Status',
    'devices' => 'Devices',
    'label' => 'Label',
    'active' => 'Active',
    'batteries' => 'Batteries',
    'charge' => 'Charge',
    'unknown' => 'Unknown',
    'footer_app' => 'Generated by %s in %s seconds.',
    'none_found' => 'None Found',
    'sound_cards' => 'Sound Cards',
    'number' => 'Number',
    'card' => 'Card',
    'message' => 'Message',
    'from_where' => 'Source',
    'mount_options' => 'Mount Options',
    'error_head' => 'Data Gathering Errors',
    'timer' => 'Timer',
    'area' => 'Area',
    'time_taken' => 'Time taken to fetch',
    'days' => 'days',
    'years' => 'years',
    'hours' => 'hours',
    'minutes' => 'minutes',
    'seconds' => 'seconds',
    'pid' => 'PID',
    'service' => 'Service',
    'services' => 'Services',
    'memory_usage' => 'Memory Usage',
    'distro' => 'Distribution',
    'cpu_arch' => 'Architecture',
    'model' => 'Model',
    'numLoggedIn' => 'Active Users',
    'virtualization' => 'Virtualization',
    'guest' => 'Guest',
    'host' => 'Host',
    'cpu_usage' => 'Overall CPU Usage',
    'port_speed' => 'Port Speed',
);
