<?php

/*
 * This file is part of Linfo (c) 2010 Joseph Gillotti.
 *
 * Linfo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Linfo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Linfo. If not, see <http://www.gnu.org/licenses/>.
 *
*/

namespace Linfo\Lang;

/*
 * Spanish translation
 */

return array(
    'header' => 'Salud e Información del Sistema',
    'core' => 'Core',
    'os' => 'SO',
    'kernel' => 'Kernel',
    'accessed_ip' => 'IP Acceso',
    'uptime' => 'Tiempo Activo',
    'hostname' => 'Hostname',
    'cpus' => 'CPUs',
    'phpversion' => 'Versión PHP',
    'webservice' => 'Servidor HTTP',
    'load' => 'Carga',
    'processes' => 'Procesos',
    'threads' => 'Hilos',
    'total' => 'Total',
    'memory' => 'Memoria',
    'type' => 'Tipo',
    'free' => 'Libre',
    'used' => 'Usado',
    'size' => 'Tamaño',
    'physical' => 'Físico',
    'swap' => 'Swap',
    'network_devices' => 'Dispositivos de Red',
    'device_name' => 'Nombre de Dispositivo',
    'amount_sent' => 'Cantidad Enviada',
    'amount_received' => 'Cantidad Recibida',
    'state' => 'Estado',
    'temps_voltages' => 'Temperaturas / Voltages',
    'path' => 'Ruta',
    'device' => 'Dispositivo',
    'value' => 'Valor',
    'hardware' => 'Hardware',
    'vendor' => 'Proveedor',
    'drives' => 'Unidades',
    'name' => 'Nombre',
    'reads' => 'Lecturas',
    'writes' => 'Escrituras',
    'filesystem_mounts' => 'Sistemas de Archivos Montados',
    'mount_point' => 'Punto de Montaje',
    'filesystem' => 'Sistema de Archivos',
    'percent_used' => 'Porcentage Usado',
    'raid_arrays' => 'RAID Arrays',
    'level' => 'Nivel',
    'status' => 'Estado',
    'devices' => 'Dispositivos',
    'label' => 'Etiqueta',
    'active' => 'Active',
    'batteries' => 'Batteries',
    'charge' => 'Charge',
    'unknown' => 'Unknown',
    'footer_app' => 'Generated by %s in %s seconds.',
    'none_found' => 'None Found',
    'sound_cards' => 'Sound Cards',
    'number' => 'Número',
    'card' => 'Card',
    'message' => 'Mensaje',
    'from_where' => 'Source',
    'mount_options' => 'Opciones de Montaje',
    'error_head' => 'Data Gathering Errors',
    'timer' => 'Temporizador',
    'area' => 'Area',
    'time_taken' => 'Time taken to fetch',
    'days' => 'días',
    'years' => 'años',
    'hours' => 'horas',
    'minutes' => 'minutos',
    'seconds' => 'segundos',
    'pid' => 'PID',
    'service' => 'Servicio',
    'services' => 'Servicios',
    'memory_usage' => 'Memory Usage',
    'distro' => 'Distribución',
    'cpu_arch' => 'Arquitectura',
    'model' => 'Modelo',
    'numLoggedIn' => 'Usuarios activos',
    'virtualization' => 'Virtualización',
    'guest' => 'Invitado',
    'host' => 'Host',
    'cpu_usage' => 'Overall CPU Usage',
    'port_speed' => 'Port Speed',
);
